# CI de Nível 01 - Disparo manual a partir de 1 clique

# nome do nosso 'pipeline'
name: 'Execução Manual'

# regras de disparo (gatilhos/triggers)
# gatilho para execução manual = workflow_dispatch
on:
  workflow_dispatch:

permissions:
  checks: write
  contents: read  

# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  unidade:
    #maquina que o job vai executar
    runs-on: ubuntu-latest

    # passos do script de build
    steps:
      - name: clonando o projeto
        uses: actions/checkout@v4

      # instalação do Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Instalando dependências do projeto
        run: npm install  

      - name: executando os testes unitários finais  
        run: yarn test

      - name: Salvando relatório de testes
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: mochawesome-report/mochawesome.html  

      - name: Publicar resultado
        uses: dorny/test-reporter@v1
        if: ${{ !cancelled() }}
        with:
          name: Test Report
          path: ./test-results/results.xml
          reporter: java-junit
          token: ${{ secrets.GITHUB_TOKEN }}

      